//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::flyers::Entity as Flyers;
pub use super::users::Entity as Users;
pub use super::videos::Entity as Videos;
pub use super::website_previews::Entity as WebsitePreviews;
